function r = grad(f,difference)
    fxb = f - translateImage(f,-1,0);
    fxf = translateImage(f,1,0) - f;
    fyb = f - translateImage(f,0,-1);
    fyf = translateImage(f,0,1) - f;
    switch(difference)
        case 'plus'
            r = sqrt( ...
                max(fxb,0).^2 + ...
                min(fxf,0).^2 + ...
                max(fyb,0).^2 + ...
                min(fyf,0).^2);
        case 'minus'
            r = sqrt( ...
                max(fxf,0).^2 + ...
                min(fxb,0).^2 + ...
                max(fyf,0).^2 + ...
                min(fyb,0).^2);
    end
end